<?php

namespace AppBundle\Repository;


//use AppBundle\Entity\Client;
//use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
}
